name: ivanalvarado-actions
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Update README Command
        run: ./gradlew run --args="--api-token $GH_API_TOKEN --login ivanalvarado --output-file README.md"
