name: ivanalvarado-actions
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permission for update_readme.sh
        run: chmod +x update_readme.sh

      - name: Run Update README Command
        run: ./update_readme.sh
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
